analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2904421391431242
  brandStrength: 0.830827
  lightness: 0.9070995165966451
  brandColors:
    - '#201D18'
    - '#CE2039'
    - '#B2A592'
    - '#921627'
    - '#DFCFB6'
  rhythmicContrast: 0.3861332077067345
typography_spectrum: 0.6557465
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9049408
favicon: null
name: SIGNS
